###
GET {{themesURL}}/

###
GET {{themesURL}}/abc

###
GET {{themesURL}}/abc/DarkTheme

###
GET {{themesURL}}/JohnerDoe/BlackTheme

###
POST {{themesURL}}/ HTTP/1.1
Content-Type: application/json

{
  "isPublic": true,
  "userName": "abc",
  "name": "DarkTheme"
}

###
POST {{themesURL}}/ HTTP/1.1
Content-Type: application/json

{
  "isPublic": false,
  "userName": "abc",
  "name": "    "
}

###
POST {{themesURL}}/ HTTP/1.1
Content-Type: application/json

{
  "isPublic": false,
  "userName": "JohnerDoe",
  "name": "BlackTheme"
}

###
PUT {{themesURL}}/JohnerDoe/BlackTheme HTTP/1.1
Content-Type: application/json

{
  "isPublic": true,
  "userName": "MarkusDoe",
  "name": "MaybeDarkTheme"
}

###
DELETE {{themesURL}}/DarkTheme/JohnerDoe HTTP/1.1