###
GET {{themesURL}}/

###

GET {{themesURL}}/private
Authorization: Bearer

###

POST {{themesURL}}/ HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
  "isPublic": true,
  "name": "DarkestTheme"
}

###
POST {{themesURL}}/ HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
  "isPublic": false,
  "userName": "abc",
  "name": "    "
}

###
POST {{themesURL}}/ HTTP/1.1
Content-Type: application/json

{
  "isPublic": false,
  "userName": "JohndDoe",
  "name": "BlackgTheme"
}

###
POST {{themesURL}}/ HTTP/1.1
Content-Type: application/json

{
  "isPublic": false,
  "userName": "JohnerDoe",
  "name": "BlackTheme"
}

###
PUT {{themesURL}}/JohnerDoe/BlackTheme HTTP/1.1
Content-Type: application/json

{
  "isPublic": true,
  "name": "MaybeDarkTheme"
}

###
DELETE {{themesURL}}/JohnerDoe/MaybeDarkTheme HTTP/1.1

###
POST {{projectsURL}} HTTP/1.1
Content-Type: application/json

{
  "token": "abc",
  "projectName": "The Best Project Known To Mankind"
}

###
GET {{projectsURL}} HTTP/1.1
Content-Type: application/json

{
  "token": "abc"
}

###
POST http://localhost:3000/api/projects